INSERT INTO Pays(nom) VALUES('États-Unis');
INSERT INTO Pays(nom) VALUES('Chine');
INSERT INTO Pays(nom) VALUES('Inde');
INSERT INTO Pays(nom) VALUES('Brésil');
INSERT INTO Pays(nom) VALUES('Royaume-Uni');
INSERT INTO Pays(nom) VALUES('Russie');
INSERT INTO Pays(nom) VALUES('Japon');
INSERT INTO Pays(nom) VALUES('Allemagne');
INSERT INTO Pays(nom) VALUES('France');
INSERT INTO Pays(nom) VALUES('Italie');
INSERT INTO Pays(nom) VALUES('Canada');
INSERT INTO Pays(nom) VALUES('Corée du Sud');
INSERT INTO Pays(nom) VALUES('Espagne');
INSERT INTO Pays(nom) VALUES('Australie');
INSERT INTO Pays(nom) VALUES('Mexique');
INSERT INTO Pays(nom) VALUES('Indonésie');
INSERT INTO Pays(nom) VALUES('Pays-Bas');
INSERT INTO Pays(nom) VALUES('Arabie saoudite');
INSERT INTO Pays(nom) VALUES('Turquie');
INSERT INTO Pays(nom) VALUES('Suisse');
INSERT INTO Pays(nom) VALUES('Suède');
INSERT INTO Pays(nom) VALUES('Pologne');
INSERT INTO Pays(nom) VALUES('Belgique');
INSERT INTO Pays(nom) VALUES('Norvège');
INSERT INTO Pays(nom) VALUES('Autriche');
INSERT INTO Pays(nom) VALUES('Irlande');
INSERT INTO Pays(nom) VALUES('Israël');
INSERT INTO Pays(nom) VALUES('Danemark');
INSERT INTO Pays(nom) VALUES('Finlande');
INSERT INTO Pays(nom) VALUES('Singapour');
INSERT INTO Pays(nom) VALUES('Portugal');
INSERT INTO Pays(nom) VALUES('Grèce');
INSERT INTO Pays(nom) VALUES('Nouvelle-Zélande');
INSERT INTO Pays(nom) VALUES('Hongrie');
INSERT INTO Pays(nom) VALUES('Émirats arabes unis');
INSERT INTO Pays(nom) VALUES('République tchèque');
INSERT INTO Pays(nom) VALUES('Malaisie');
INSERT INTO Pays(nom) VALUES('Qatar');
INSERT INTO Pays(nom) VALUES('Koweït');
