INSERT INTO Compte(id, nom) VALUES(DEFAULT,'Freddy Mercury');
INSERT INTO Compte(id, nom) VALUES(DEFAULT,'lau_fst');
INSERT INTO Compte(id, nom) VALUES(DEFAULT,'Queen');
INSERT INTO Compte(id, nom) VALUES(DEFAULT,'Hayilat');
INSERT INTO Compte(id, nom) VALUES(DEFAULT,'Brian May');
INSERT INTO Compte(id, nom) VALUES(DEFAULT,'Roger Taylor');
INSERT INTO Compte(id, nom) VALUES(DEFAULT,'Gambi');
INSERT INTO Compte(id, nom) VALUES(DEFAULT,'Laure Ploix');
INSERT Into Compte(id, nom) VALUES(Default, 'iris_gri');
INSERT Into Compte(id, nom) VALUES(Default, 'adeeee');
INSERT INTO Compte(id, nom) VALUES(DEFAULT,'no_gru');
INSERT INTO Compte(id, nom) VALUES(DEFAULT,'emmanuel_macron');
INSERT INTO Compte(id, nom) VALUES(DEFAULT,'PNL');
INSERT INTO Compte(id, nom) VALUES(DEFAULT,'Xavier Guchet');
INSERT INTO Compte(id, nom) VALUES(DEFAULT,'Jacques Chirac');
INSERT INTO Compte(id, nom) VALUES(DEFAULT,'Xxx_Hater_xxX');
INSERT INTO Compte(id, nom) VALUES(DEFAULT,'jump_max');
INSERT INTO Compte(id, nom) VALUES(DEFAULT,'chimpanze_combat');
INSERT INTO Compte(id, nom) VALUES(DEFAULT, 'Michael Jackson');
INSERT INTO Compte(id, nom) VALUES(DEFAULT, 'Elvis Presley');
INSERT INTO Compte(id, nom) VALUES(DEFAULT, 'Bob Dylan');
INSERT INTO Compte(id, nom) VALUES(DEFAULT, 'Madonna');
INSERT INTO Compte(id, nom) VALUES(DEFAULT, 'John Lennon');
INSERT INTO Compte(id, nom) VALUES(DEFAULT, 'Paul McCartney');
INSERT INTO Compte(id, nom) VALUES(DEFAULT, 'David Bowie');
INSERT INTO Compte(id, nom) VALUES(DEFAULT, 'Stevie Wonder');
INSERT INTO Compte(id, nom) VALUES(DEFAULT, 'Freddie Mercury');
INSERT INTO Compte(id, nom) VALUES(DEFAULT, 'Prince');
INSERT INTO Compte(id, nom) VALUES(DEFAULT, 'Louis Armstrong');
INSERT INTO Compte(id, nom) VALUES(DEFAULT, 'Tupac Shakur');
INSERT INTO Compte(id, nom) VALUES(DEFAULT, 'Beyoncé');
INSERT INTO Compte(id, nom) VALUES(DEFAULT, 'Daft Punk');
INSERT INTO Compte(id, nom) VALUES(DEFAULT, 'Calvin Harris');
INSERT INTO Compte(id, nom) VALUES(DEFAULT, 'Rahzel');
INSERT INTO Compte(id, nom) VALUES(DEFAULT, 'Johnny Cash');
INSERT INTO Compte(id, nom) VALUES(DEFAULT, 'Chief Keef');
INSERT INTO Compte(id, nom) VALUES(DEFAULT, 'Arctic Monkeys');
INSERT INTO Compte(id, nom) VALUES(DEFAULT, 'Mac DeMarco');
INSERT INTO Compte(id, nom) VALUES(DEFAULT, 'Lofi Girl');
INSERT INTO Compte(id, nom) VALUES(DEFAULT, 'Mozart');
INSERT INTO Compte(id, nom) VALUES(DEFAULT, 'Chopin');
INSERT INTO Compte(id, nom) VALUES(DEFAULT, 'Eminem');
INSERT Into Compte(id, nom) VALUES(Default, 'Thomas Bangalter');
INSERT Into Compte(id, nom) VALUES(Default, 'The Beatles');
