INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'lau_fst'), (SELECT id FROM GenresMusicaux WHERE nom = 'Rock'));
INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'lau_fst'), (SELECT id FROM GenresMusicaux WHERE nom = 'Blues'));
INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'lau_fst'), (SELECT id FROM GenresMusicaux WHERE nom = 'Disco'));
INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'lau_fst'), (SELECT id FROM GenresMusicaux WHERE nom = 'Funk'));
INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'lau_fst'), (SELECT id FROM GenresMusicaux WHERE nom = 'Métal'));
INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'lau_fst'), (SELECT id FROM GenresMusicaux WHERE nom = 'Reggaeton'));
INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'jump_max'), (SELECT id FROM GenresMusicaux WHERE nom = 'Lo-fi'));
INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'jump_max'), (SELECT id FROM GenresMusicaux WHERE nom = 'Rap'));
INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'jump_max'), (SELECT id FROM GenresMusicaux WHERE nom = 'Indie'));
INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'jump_max'), (SELECT id FROM GenresMusicaux WHERE nom = 'Hip-hop'));
INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'jump_max'), (SELECT id FROM GenresMusicaux WHERE nom = 'Beatbox'));
INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'iris_gri'), (SELECT id FROM GenresMusicaux WHERE nom = 'Disco'));
INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'iris_gri'), (SELECT id FROM GenresMusicaux WHERE nom = 'Pop'));
INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'iris_gri'), (SELECT id FROM GenresMusicaux WHERE nom = 'RNB'));
INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'iris_gri'), (SELECT id FROM GenresMusicaux WHERE nom = 'Reggaeton'));
INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'iris_gri'), (SELECT id FROM GenresMusicaux WHERE nom = 'Funk'));
INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'emmanuel_macron'), (SELECT id FROM GenresMusicaux WHERE nom = 'Drill'));
INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'emmanuel_macron'), (SELECT id FROM GenresMusicaux WHERE nom = 'Rap'));
INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'emmanuel_macron'), (SELECT id FROM GenresMusicaux WHERE nom = 'Grunge'));
INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'emmanuel_macron'), (SELECT id FROM GenresMusicaux WHERE nom = 'Métal'));
INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'emmanuel_macron'), (SELECT id FROM GenresMusicaux WHERE nom = 'Métal'));
INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'Xavier Guchet'), (SELECT id FROM GenresMusicaux WHERE nom = 'Indie'));
INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'Laure Ploix'), (SELECT id FROM GenresMusicaux WHERE nom = 'Rap'));
INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'no_gru'), (SELECT id FROM GenresMusicaux WHERE nom = 'Reggae'));
INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'Xxx_Hater_xxX'), (SELECT id FROM GenresMusicaux WHERE nom = 'Soul'));
INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'chimpanze_combat'), (SELECT id FROM GenresMusicaux WHERE nom = 'Electro'));
INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'adeeee'), (SELECT id FROM GenresMusicaux WHERE nom = 'Indie'));
INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'Jacques Chirac'), (SELECT id FROM GenresMusicaux WHERE nom = 'EDM'));
INSERT INTO Assos_Utilisateurice_GenreMusicaux((SELECT id FROM Profil_Utilisateurice WHERE nom = 'chimpanze_combat'), (SELECT id FROM GenresMusicaux WHERE nom = 'Beatbox'));