INSERT INTO Profil_Utilisateurice VALUES(1, 'lau_fst', 'lau@example.com', 'mdp123456', '2020-10-27', 'premium', '[{"nom":rock}, {"nom":pop}]');
INSERT INTO Profil_Utilisateurice VALUES(2, 'emmanuel_macron', 'emmanuel.macron@example.com','BenallaIl0v3U','2024-01-01','regulier', '[{"nom":"rock"}, {"nom":"metal"}]');
INSERT INTO Profil_Utilisateurice VALUES(3, 'Xavier Guchet', 'xavier.guchet@example.com', 'xavier4312','2022-10-23','regulier', '[{"nom":"Jazz"}, {"nom":"Classique"}]');
INSERT INTO Profil_Utilisateurice VALUES(4, 'Laure Ploix', 'laure.ploix@example.com', 'bvqjkr5', '2021-05-12', 'premium', '[{"nom":"Rock"}, {"nom":"Rap"}]');
INSERT INTO Profil_Utilisateurice VALUES(5, 'no_gru', 'no.gruget@example.com', 'skateboard', '2020-12-30', 'premium', '[{"nom": "Indie"}]');
INSERT INTO Profil_Utilisateurice VALUES(6, 'Xxx_Hater_xxX', 'ihateeverything@example.com', 'xxxx11xxxx', '2023-04-25', 'regulier', '[{"nom":"Rap"}, {"nom":"Hip-hop"}]');
INSERT INTO Profil_Utilisateurice VALUES(7, 'jump_max', 'max@example.com', 'bjbvkfjhjk,yfuyqsu24345gfherr', '2018-01-21', 'premium', '[{"nom":"Rock"}, {"nom":"Pop"}]');
INSERT INTO Profil_Utilisateurice VALUES(8, 'chimpanze_combat', 'chimpanze.combat@example.com', 'hahahahaCOMBAT', '2023-06-15', 'premium', '["nom":"Lo-fi"]');
INSERT INTO Profil_Utilisateurice VALUES(9, 'iris_gri', 'irisaubresil@example.com', 'stflcaldm,aenpqmaf_milp', '2019-03-11', 'premium', '[{"nom":"EDM"}, {"nom":"Electro"}]');
INSERT INTO Profil_Utilisateurice VALUES(10, 'adeeee', 'ade@example.com', 'gb2004', '2019-03-11', 'premium' , '[{"nom":"Rap"}, {"nom":"Hip-hop"}]');
INSERT INTO Profil_Utilisateurice VALUES(11, 'Jacques Chirac', 'jacques.chirac@example.com', 'pommes', '1999-01-16', 'regulier' , '[{"nom":"Classique"}, {"nom":"Jazz"}]');