INSERT INTO Assos_Utilisateurice_Utilisateurice VALUES((SELECT id FROM Compte WHERE nom = 'lau_fst'), (SELECT id FROM Compte WHERE nom = 'jump_max'));
INSERT INTO Assos_Utilisateurice_Utilisateurice VALUES((SELECT id FROM Compte WHERE nom = 'lau_fst'), (SELECT id FROM Compte WHERE nom = 'iris_gri'));
INSERT INTO Assos_Utilisateurice_Utilisateurice VALUES((SELECT id FROM Compte WHERE nom = 'iris_gri'), (SELECT id FROM Compte WHERE nom = 'jump_max'));
INSERT INTO Assos_Utilisateurice_Utilisateurice VALUES((SELECT id FROM Compte WHERE nom = 'iris_gri'), (SELECT id FROM Compte WHERE nom = 'adeeee'));
INSERT INTO Assos_Utilisateurice_Utilisateurice VALUES((SELECT id FROM Compte WHERE nom = 'iris_gri'), (SELECT id FROM Compte WHERE nom = 'Laure Ploix'));
INSERT INTO Assos_Utilisateurice_Utilisateurice VALUES((SELECT id FROM Compte WHERE nom = 'no_gru'), (SELECT id FROM Compte WHERE nom = 'iris_gri'));
INSERT INTO Assos_Utilisateurice_Utilisateurice VALUES((SELECT id FROM Compte WHERE nom = 'no_gru'), (SELECT id FROM Compte WHERE nom = 'adeeee'));
INSERT INTO Assos_Utilisateurice_Utilisateurice VALUES((SELECT id FROM Compte WHERE nom = 'no_gru'), (SELECT id FROM Compte WHERE nom = 'Laure Ploix'));
INSERT INTO Assos_Utilisateurice_Utilisateurice VALUES((SELECT id FROM Compte WHERE nom = 'lau_fst'), (SELECT id FROM Compte WHERE nom = 'Laure Ploix'));
INSERT INTO Assos_Utilisateurice_Utilisateurice VALUES((SELECT id FROM Compte WHERE nom = 'lau_fst'), (SELECT id FROM Compte WHERE nom = 'no_gru'));
INSERT INTO Assos_Utilisateurice_Utilisateurice VALUES((SELECT id FROM Compte WHERE nom = 'lau_fst'), (SELECT id FROM Compte WHERE nom = 'adeeee'));
INSERT INTO Assos_Utilisateurice_Utilisateurice VALUES((SELECT id FROM Compte WHERE nom = 'jump_max'), (SELECT id FROM Compte WHERE nom = 'no_gru'));
INSERT INTO Assos_Utilisateurice_Utilisateurice VALUES((SELECT id FROM Compte WHERE nom = 'lau_fst'), (SELECT id FROM Compte WHERE nom = 'chimpanze_combat'));
INSERT INTO Assos_Utilisateurice_Utilisateurice VALUES((SELECT id FROM Compte WHERE nom = 'jump_max'), (SELECT id FROM Compte WHERE nom = 'chimpanze_combat'));
INSERT INTO Assos_Utilisateurice_Utilisateurice VALUES((SELECT id FROM Compte WHERE nom = 'Xxx_Hater_xxX'), (SELECT id FROM Compte WHERE nom = 'emmanuel_macron'));
INSERT INTO Assos_Utilisateurice_Utilisateurice VALUES((SELECT id FROM Compte WHERE nom = 'Xxx_Hater_xxX'), (SELECT id FROM Compte WHERE nom = 'Jacques Chirac'));
INSERT INTO Assos_Utilisateurice_Utilisateurice VALUES((SELECT id FROM Compte WHERE nom = 'emmanuel_macron'), (SELECT id FROM Compte WHERE nom = 'Jacques Chirac'));
INSERT INTO Assos_Utilisateurice_Utilisateurice VALUES((SELECT id FROM Compte WHERE nom = 'Xavier Guchet'), (SELECT id FROM Compte WHERE nom = 'chimpanze_combat'));
INSERT INTO Assos_Utilisateurice_Utilisateurice VALUES((SELECT id FROM Compte WHERE nom = 'Xavier Guchet'), (SELECT id FROM Compte WHERE nom = 'jump_max'));